/***************************
* Autor: Equipo 2
* Estructuras Discretas
* 2024-1
****************************/

function valuap(respuest) {
    var reto;
    if (parseInt(respuest) == this.correcta) {
        // var reto;
        alert("Es correcta");
        reto = true;
        return reto;
    } else {
        alert("Es false");
        return reto;
    }
}

function pregunta(pregun, respuesta1, respuesta2, respuesta3, respuesta4, correcta) {
    this.pregun = pregun;
    this.respuestas = [];
    this.respuestas[0] = respuesta1;
    this.respuestas[1] = respuesta2;
    this.respuestas[2] = respuesta3;
    this.respuestas[3] = respuesta4;
    this.correcta = parseInt(correcta);
    this.ocupado = false;
    this.valuap = valuap;
}

var retorno = [];
var preguntas = [];

preguntas[0] = new pregunta("(1)¿Qué es la probabilidad condicional?","a) La probabilidad de que ocurra el evento A","b) La probabilidad de que ocurra el evento B","c) La probabilidad de que ocurran A y B juntos","d) La probabilidad de que ocurra el evento A dado que el evento B ya ha ocurrido",3);
preguntas[1] = new pregunta("(2)¿Cómo se denota la probabilidad condicional de que ocurra A dado que B ha ocurrido?","a) P(A | B)","b) P(A / B)","c) P(A & B)","d) P(A * B)",0);
preguntas[2] = new pregunta("(3)¿Cuál es la fórmula para calcular la probabilidad condicional de A dado B?","a) P(A | B) = p(A) + p(B)","b) P(A | B) = p(A - B) / p(B)","c) P(A | B) = p(A * B) / p(B)","d) P(A | B) = p(A∩B) / p(B)",3);
preguntas[3] = new pregunta("(4)Según el teorema, ¿cómo se relaciona la probabilidad condicional de A y su complemento?","a) Son iguales","b) Son independientes","c) La probabilidad condicional de A es igual a 1 menos la probabilidad condicional de su complemento","d) No tienen relación",2);
preguntas[4] = new pregunta("(5)¿En qué contexto se utiliza un diagrama de Venn?","a) Para calcular la probabilidad de un evento A","b) Para representar visualmente las relaciones entre conjuntos","c) Para calcular la probabilidad de un evento B","d) Para ilustrar la probabilidad condicional",1);
preguntas[5] = new pregunta("(6)¿Qué representan los conjuntos A y B en el contexto de la probabilidad condicional?","a) Son eventos independientes","b) Son eventos mutuamente excluyentes","c) Son eventos relacionados con un experimento E","d) Son eventos para calcular la probabilidad condicional de que B ocurra dado que A ya ha ocurrido",3);
preguntas[6] = new pregunta("(7)¿Cómo se reduce el espacio muestral al calcular P(B | A)?","a) Se mantiene igual","b) Se amplía","c) Se reduce de S a A","d) Se reduce de A a S",2);
preguntas[7] = new pregunta("(8)¿Qué se busca verificar con la probabilidad condicional?","a) La probabilidad de que ocurra un evento B","b) La probabilidad de que ocurra un evento A","c) Conjuntos de suposiciones o hipótesis","d) La probabilidad de que A y B ocurran juntos",2);
preguntas[8] = new pregunta("(9)¿Cuál es una de las aplicaciones más significativas de la probabilidad condicional?","a) Calcular la probabilidad total de un evento","b) Evaluar la probabilidad de ocurrencia de un evento A","c) Simplificar el cálculo de intersecciones de eventos en ciertos experimentos","d) Establecer la independencia de eventos",2);
preguntas[9] = new pregunta("(10)¿Cuál es el objetivo de la probabilidad condicional?","a) Calcular la probabilidad de eventos no relacionados","b) Evaluar la probabilidad de ocurrencia de un evento A","c) Determinar la probabilidad de que ocurra un evento B","d) Evaluar la probabilidad de que ocurra un evento A dado que otro evento B ya ha ocurrido",3);
preguntas[10] = new pregunta("(11)¿Qué se utiliza para representar visualmente las relaciones entre conjuntos en el contexto de la probabilidad condicional?","a) Diagrama de árbol","b) Diagrama de Venn","c) Diagrama de barras","d) Diagrama de flujo",1);
preguntas[11] = new pregunta("(12)¿Cuál es la relación entre la probabilidad de A dado B y la probabilidad de A en el espacio muestral original?","a) Son iguales","b) Son inversamente proporcionales","c) La probabilidad condicional de A dado B se calcula en función de la probabilidad de A en el espacio muestral original","d) No tienen relación",2);
preguntas[12] = new pregunta("(13)¿Qué se busca calcular al evaluar P(B | A)?","a) La probabilidad de que ocurra B independientemente de A","b) La probabilidad de que ocurra B en el contexto del espacio muestral original","c) La probabilidad de que ocurra B dado que A ya ha ocurrido","d) La probabilidad de que ocurran A y B simultáneamente",2);
preguntas[13] = new pregunta("(14)¿Qué se convierte en el espacio muestral al afirmar que el evento A ya ha tenido lugar?","a) El evento B","b) El evento A","c) El espacio muestral original","d) A se convierte en el espacio muestral",3);
preguntas[14] = new pregunta("(15)¿Qué se evalúa al calcular la probabilidad condicional de que ocurra B dado que A ya ha ocurrido?","a) La probabilidad de que ocurra A","b) La probabilidad de que ocurra B en cualquier contexto","c) La probabilidad de que ocurra B en el contexto de A","d) La probabilidad de que ocurran A y B de forma independiente.",2);
preguntas[15] = new pregunta("(16)¿Cuándo decimos que dos eventos, A y B, son independientes?","a) Cuando la probabilidad de que ocurra A sea igual a la probabilidad de que ocurra B.","b) Cuando la probabilidad de que ocurra A cambia si el evento B ocurre.","c) Cuando la probabilidad condicional de que ocurra A dado que ocurrió B es igual a la probabilidad original de que ocurra A.","d) Cuando la probabilidad de que ocurran A y B juntos es diferente al producto de las probabilidades individuales de A y B.",2);
preguntas[16] = new pregunta("(17)¿Qué significa que A y B son eventos independientes?","a) Que la probabilidad de que ocurra A depende de la ocurrencia de B.","b) Que la probabilidad de que ocurra B depende de la ocurrencia de A.","c) Que la probabilidad condicional de que ocurra A dado que ocurrió B es igual a la probabilidad original de que ocurra A.","d) Que la probabilidad de que ambos eventos A y B ocurran juntos es igual al producto de las probabilidades individuales de A y B", 3);
preguntas[17] = new pregunta("(18)¿Qué se requiere para que n sucesos sean mutuamente independientes?","a) Que todos los sucesos sean independientes entre sí.","b) Que al menos dos sucesos sean independientes.","c) Que para cualquier grupo de sucesos diferentes Ai, Aj ... Am se cumpla que p(Ai, Aj ... Am) = p(Ai)p(Aj) ... p(Am).","d) No se pueden tener n sucesos mutuamente independientes.",2);
preguntas[18] = new pregunta("(19)¿Qué significa que las pruebas son mutuamente independientes en problemas prácticos?","a) Que el resultado de una prueba afecta el resultado de otra.","b) Que el resultado de una prueba no afecta el resultado de otra.","c) Que todas las pruebas son iguales.","d) Que las pruebas son independientes dos a dos.",1);
preguntas[19] = new pregunta("(20)¿Qué condición debe cumplirse para que un experimento consista en n pruebas independientes?","a) Que el espacio muestral S sea el producto Cartesiano de n conjuntos S1, S2, ..., Sn.","b) Que la probabilidad de ocurrencia de un evento de un solo elemento A⊂S sea igual al producto de las probabilidades de ocurrencia de los eventos correspondientes de un solo elemento Ai⊂Si.", "c) Que todos los sucesos sean independientes entre sí.","d) No hay condiciones específicas.",1);
preguntas[20] = new pregunta("(21)¿Qué ocurre cuando A y B son eventos independientes en términos de probabilidad condicional?","a) La probabilidad de que ocurra A se ve afectada por la ocurrencia de B.","b) La probabilidad de que ocurra B se ve afectada por la ocurrencia de A.","c) Saber que B ha ocurrido modifica la probabilidad de que A ocurra","d) La probabilidad de que ocurra A no se ve afectada por la ocurrencia de B.",3);
preguntas[21] = new pregunta("(22)¿Cuál es una característica de los eventos mutuamente excluyentes?","a) Pueden ocurrir simultáneamente.","b) No pueden ocurrir al mismo tiempo.","c) Son necesariamente independientes.","d) La probabilidad de que ocurran A y B juntos es igual al producto de las probabilidades individuales de A y B.",1);
preguntas[22] = new pregunta("(23)¿Qué diferencia fundamental existe entre independencia y mutua exclusividad?","a) La independencia significa que dos eventos no pueden ocurrir al mismo tiempo, mientras que la mutua exclusividad se basa en la probabilidad condicional.","b) Son conceptos completamente iguales.","c) La independencia se refiere a eventos que no pueden ocurrir simultáneamente, mientras que la mutua exclusividad se relaciona con la probabilidad condicional.","d) La mutua exclusividad implica que los eventos son independientes.",2);
preguntas[23] = new pregunta("(24)¿Qué condiciones se deben cumplir para que tres eventos, A, B y C, sean independientes?","a) p(A∩B) = p(A)p(B) y p(A∩C) = p(A)p(C)","b) p(B∩C) = p(B)p(C) y p(A∩B∩C) = p(A)p(B)p(C)","c) p(A∩B) = p(A)p(B), p(A∩C) = p(A)p(C) y p(B∩C) = p(B)p(C)","d) p(A∩B∩C) = p(A)p(B)p(C)",3);
preguntas[24] = new pregunta("(25)¿Por qué es importante la independencia en la asignación de probabilidades en problemas prácticos?","a) No tiene importancia en la asignación de probabilidades","b) Facilita el cálculo de diversas posibilidades al asignar probabilidades de manera particular.","c) Solo se aplica en situaciones especiales.","d) Complica la asignación de probabilidades en problemas prácticos.",1);
preguntas[25] = new pregunta("(26)¿Qué significa que la probabilidad de que ocurra A no se ve afectada por la ocurrencia de B cuando A y B son independientes?","a) Que la probabilidad de que ocurra A cambia si B ocurre.","b) Que p(A | B) ≠ p(A).","c) Que la probabilidad de que ocurra A no cambia independientemente de si B ocurre o no","d) Que la probabilidad de que ocurra B cambia si A ocurre.",2);
preguntas[26] = new pregunta("(27)¿Qué condición se debe cumplir para que tres eventos, A, B y C, sean mutuamente independientes?","a) p(A∩B) = p(A)p(B) y p(A∩C) = p(A)p(C)","b) p(B∩C) = p(B)p(C) y p(A∩B∩C) = p(A)p(B)p(C)","c) p(A∩B) = p(A)p(B) y p(A∩C) = p(A)p(C) y p(B∩C) = p(B)p(C)","d) Ninguna de las anteriores",3);
preguntas[27] = new pregunta("(28)¿Qué es la probabilidad discreta?","a) Un enfoque de la teoría de la probabilidad que se utiliza cuando estamos tratando con un conjunto infinito de resultados posibles.","b) Un enfoque de la teoría de la probabilidad que se utiliza cuando estamos tratando con un conjunto finito o numerable de resultados posibles en un experimento.","c) Un enfoque de la teoría de la probabilidad que se utiliza en eventos continuos","d) Un enfoque de la teoría de la probabilidad que se aplica solo en eventos discretos.",1);
preguntas[28] = new pregunta("(29)¿Qué principio establece el Axioma 1 de la probabilidad discreta?","a) No existe ningún principio asociado con el Axioma 1.","b) La probabilidad total de todos los resultados debe ser igual a 1.","c) La probabilidad de un resultado individual debe ser igual o mayor que cero.","d) La probabilidad de un resultado individual debe ser igual o mayor que uno.",2);
preguntas[29] = new pregunta("(30)¿Cuál es el principio establecido por el Axioma 2 de la probabilidad discreta?","a) La probabilidad de que ocurran varios eventos independientes es igual al producto de sus probabilidades individuales.","b) La probabilidad de que al menos un evento ocurra es igual a la suma de las probabilidades de todos los eventos.","c) La probabilidad total de todos los resultados debe ser igual a 0.","d) La suma de las probabilidades de todos los resultados en el conjunto de resultados posibles debe ser igual a 1 (Σpi = 1).",3);
preguntas[30] = new pregunta("(31)¿Qué establece la propiedad de aditividad según el Axioma 3 de la probabilidad discreta?","a) La probabilidad de que ocurran eventos mutuamente excluyentes es igual al producto de sus probabilidades individuales.","b) La probabilidad de que ocurran eventos mutuamente excluyentes es igual a la suma de las probabilidades individuales de esos eventos.","c) La probabilidad de que ocurran eventos independientes es igual al producto de sus probabilidades individuales.","d) La probabilidad de que ocurran eventos no excluyentes es igual a la resta de las probabilidades individuales.",1);
preguntas[31] = new pregunta("(32)¿Cuál es el espacio muestral discreto en el ejemplo del lanzamiento de una moneda?","a) El espacio muestral no se menciona en el ejemplo.","b) El espacio muestral discreto es Ω","c) El espacio muestral discreto es el conjunto de todos los números reales.","d) El espacio muestral discreto es el conjunto de dos resultados posibles: cara (w1) y cruz (w2).",3);
preguntas[32] = new pregunta("(33)¿Qué asociamos a cada resultado en el espacio muestral en el lanzamiento de una moneda?","a) Una letra del alfabeto.","b) Un número complejo.","c) Una probabilidad específica.","d) Un evento independiente.",2);
preguntas[33] = new pregunta("(34)¿Qué representa P(w1) en el contexto del lanzamiento de una moneda?","a) La probabilidad de obtener un número entero.","b) La probabilidad de obtener un número impar.","c) La probabilidad de obtener cara.","d) La probabilidad de obtener cruz.",2);
preguntas[34] = new pregunta("(35)¿Qué significa p1 + p2 = 1 en un lanzamiento de una moneda justa y simétrica?","a) Significa que la probabilidad de obtener cara o cruz es 1/4 cada una.","b) Significa que la probabilidad de obtener cara o cruz es 1/2 cada una.","c) No tiene ningún significado.","d) Significa que la probabilidad de obtener cara o cruz es 1 cada una.",1);
preguntas[35] = new pregunta("(36)¿Qué principio se cumple en un lanzamiento de una moneda justa y simétrica en relación con los axiomas de la probabilidad discreta?","a) Los axiomas de la probabilidad discreta no se cumplen en un lanzamiento de una moneda.","b) Se cumple el Axioma 1, pero no el Axioma 2.","c) Se cumplen los Axiomas 1 y 2, pero no el Axioma 3.","d) Se cumplen los Axiomas 1, 2 y 3 de la probabilidad discreta.",3);
preguntas[36] = new pregunta("(37)¿Cuál de las siguientes afirmaciones describe adecuadamente la probabilidad discreta?","a) Se aplica solo en eventos continuos.","b) Se utiliza en un conjunto infinito de resultados posibles.","c) Es un enfoque de la teoría de la probabilidad que se utiliza cuando estamos tratando con un conjunto finito o numerable de resultados posibles en un experimento.","d) No tiene restricciones ni principios.",2);
preguntas[37] = new pregunta("(38)¿Cuál es la condición principal que debe cumplir un espacio muestral para que se aplique la probabilidad discreta?","a) Ser un conjunto infinito de resultados posibles.","b) Estar compuesto por eventos independientes.","c) Ser un conjunto finito o numerable de resultados posibles en un experimento.","d) No tiene ninguna condición",2);
preguntas[38] = new pregunta("(39)¿Cuál es el resultado esperado en un lanzamiento de una moneda justa y simétrica según la probabilidad discreta?","a) El resultado esperado es cara con probabilidad 1.","b) El resultado esperado es cruz con probabilidad 0.","c) El resultado esperado es cara o cruz con probabilidad 1/2 cada uno.","d) El resultado esperado es indeterminado.",2);
preguntas[39] = new pregunta("(40)¿Qué describe el Teorema de Bayes?","a) La forma de calcular probabilidades a priori.","b) Cómo se obtienen probabilidades a posteriori.","c) Cómo calcular la probabilidad de un evento dado su efecto observado.","d) Cómo calcular la probabilidad de un evento antes de que ocurra.",2);
preguntas[40] = new pregunta("(41)¿Cómo se expresan las probabilidades a priori en el Teorema de Bayes?","a) P(A|B1) y P(B1)","b) P(A|B2) y P(B2)","c) P(B2)","d) P(B1) y P(B2)",3);
preguntas[41] = new pregunta("(42)¿Qué permite calcular el Teorema de Bayes?","a) La probabilidad de un evento dado su efecto observado.","b) La probabilidad de un evento sin información adicional.","c) La probabilidad de un evento antes de que ocurra.","d) La probabilidad de un evento posterior a su ocurrencia.",0);
preguntas[42] = new pregunta("(43)¿Cuál es el propósito de las probabilidades a priori en el Teorema de Bayes?","a) Representar la probabilidad de eventos observados","b) Reflejar la probabilidad de eventos después de la prueba.","c) Representar las creencias iniciales sobre eventos antes de obtener nueva evidencia.","d) Reflejar la probabilidad de eventos independientes.",2);
preguntas[43] = new pregunta("(44)¿Qué fórmula se utiliza para calcular P(B1|A) en el Teorema de Bayes?","a) P(A|B2)P(B2) / [ P(A|B1)P(B1) + P(A|B2)P(B2) ]","b) P(A|B1)P(B1) / [ P(A|B1)P(B1) + P(A|B2)P(B2) ]","c) P(A|B1)P(B1) / [ P(A|B2)P(B2) + P(A|B1)P(B1) ]","d) P(B2|A)P(B1) / [ P(A|B2)P(B2) + P(A|B1)P(B1) ]",1);
preguntas[44] = new pregunta("(45)¿Qué representa P(A|B2) en el contexto del Sr. K y su prueba médica?","a) La probabilidad de que la prueba sea positiva si el Sr. K tiene la enfermedad.","b) La probabilidad de que la prueba sea negativa si el Sr. K no tiene la enfermedad.","c) La probabilidad de que el Sr. K realmente tenga la enfermedad dado que la prueba fue negativa.","d) La probabilidad de que la prueba sea positiva si el Sr. K no tiene la enfermedad.",3);
preguntas[45] = new pregunta("(46)¿De qué otra manera se llama el teorema de Bayes?","a) Método de Bayes para la probabilidad “binomial”.","b) Regla de Bayes para la probabilidad de “consecuencias”.","c) Fórmula para la probabilidad de las “causas”.","d) Teorema de “situaciones”.",2);
preguntas[46] = new pregunta("(47)¿Qué importancia tiene la teoría de la probabilidad en la actualidad?","a) Tiene poca importancia en la mayoría de las áreas.","b) Es fundamental solo en la industria de los juegos de azar.","c) Es una herramienta importante en la mayoría de las áreas de ingeniería, ciencias y administración.","d) Es relevante únicamente en el campo de la medicina.",2);
preguntas[47] = new pregunta("(48)¿Qué ciencia se construye sobre la base del Teorema de Bayes en la Teoría de la Probabilidad?","a) En las artes.","b) En la medicina.","c) Las ciencias naturales.","d) La Inferencia Estadística.",3);
preguntas[48] = new pregunta("(49)¿Cuál se considera el teorema más importante de la Teoría de la Probabilidad?","a) Teorema de Bayes.","b) Probanilidad discreta","c) Probabilidad condicional","d) Independencias",0);
preguntas[49] = new pregunta("(50)¿Por qué se considera al Teorema de Bayes como fundamental en la Teoría de la Probabilidad?","a) Es el teorema más antiguo en la Teoría de la Probabilidad.","b) Porque solo se aplica en casos específicos.","c) Constituye la base de toda una ciencia.","d) Estimación de frecuencia de eventos.",2);
